# Generated by Django 4.2.4 on 2023-09-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_room_options_room_host_room_topic_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created', 'updated']},
        ),
    ]
